name: Build and Release

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        include:
          - os: ubuntu-20.04
            platform: linux
            arch: x86_64
            name: ubuntu20
          - os: ubuntu-22.04
            platform: linux
            arch: x86_64  
            name: ubuntu22
          - os: macos-14
            platform: macos
            arch: arm64
            name: macos
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30  # Prevent jobs from hanging indefinitely
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug runner info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Matrix OS: ${{ matrix.os }}"
        echo "Matrix Platform: ${{ matrix.platform }}"
        echo "Matrix Arch: ${{ matrix.arch }}"
        echo "Available disk space:"
        df -h
        echo "System info:"
        uname -a
    
    - name: Install dependencies (Ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          pkg-config \
          curl \
          libcurl4-openssl-dev
    
    - name: Install dependencies (macOS)
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install cmake curl pkg-config
    
    - name: Make build script executable
      run: chmod +x scripts/build-static.sh
    
    - name: Build using our build script
      run: ./scripts/build-static.sh
      env:
        NEURON_OS: ${{ startsWith(matrix.os, 'ubuntu') && 'Linux' || 'Darwin' }}
        NEURON_ARCH: ${{ matrix.arch }}
        NEURON_NAME: ${{ matrix.name }}
        CI: true
    
    - name: Show binary info
      run: |
        file dist/neuron-${{ matrix.name }}
        ls -lh dist/neuron-${{ matrix.name }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: neuron-${{ matrix.name }}
        path: dist/neuron-${{ matrix.name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: Prepare release assets
      run: |
        mkdir -p release
        find artifacts -name "neuron-*" -type f -exec cp {} release/ \;
        ls -la release/
    
    - name: Generate checksums
      run: |
        cd release
        sha256sum * > checksums.txt
        cat checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        draft: false
        prerelease: ${{ contains(github.ref, '-') }}
        generate_release_notes: true
        body: |
          ## 🧬 Neuron AI Release ${{ github.ref_name }}
          
          ### Installation
          
          **Quick install (recommended):**
          ```bash
          curl -sSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          ```
          
          **Manual download:**
          - **macOS (Intel)**: `neuron-macos-x86_64`
          - **macOS (Apple Silicon)**: `neuron-macos-arm64`  
          - **Linux (Intel)**: `neuron-linux-x86_64`
          - **Linux (ARM64)**: `neuron-linux-arm64`
          
          ### Setup
          1. Download the appropriate binary for your platform
          2. Make it executable: `chmod +x neuron-*`
          3. Move to PATH: `sudo mv neuron-* /usr/local/bin/neuron`
          4. Set API key: `export NEURON_API_KEY=your_key`
          5. Try it: `neuron run "show disk usage"`
          
          ### Checksums
          Verify your download with `sha256sum`:
          ```
          $(cat release/checksums.txt)
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}